Return only channels for query string starting with '@'
lbryio/lighthouse pull request #33
Opened 2020-09-06 09:09 UTC by ioancole

For query string starting with '@', return only list of matching channels.
Else return list of results as before.

2020-09-09 20:05 UTC, kauffj commented
thanks @ioancole, this will get looked at shortly

would be interested in making more contributions here? you can also email me at jeremy@lbry.com

2020-09-09 20:14 UTC, tiger5226 requested changes

2020-09-09 20:14 UTC, tiger5226 commented on app/actions/auto_complete.go
> +        mmATD = mmATD.Field("value.Claim.stream.metadata.author")
you want to use the claim name not the author field.

2020-09-09 20:16 UTC, tiger5226 commented
https://github.com/lbryio/lighthouse/blob/master/app/actions/search/query.go#L182 here is an area in the search query where we do something similar if you want to take another stab at it.

2020-09-10 01:24 UTC, ioancole commented
Yes fair enough, thanks!

2020-10-13 14:31 UTC, kauffj commented
@ioancole still planning to finish this?

2020-10-14 20:45 UTC, tiger5226 approved these changes

2020-10-14 20:46 UTC, merged